# Generated by Django 4.1 on 2023-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.CharField(max_length=120),
        ),
    ]
