# Generated by Django 4.1 on 2023-01-24 15:03

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('file', models.FileField(upload_to=builtins.any)),
                ('title_of_book', models.CharField(max_length=255)),
                ('Author_of_book', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('visibility', models.BooleanField(default=True)),
                ('cost_of_book', models.FloatField(max_length=10)),
                ('Year', models.CharField(max_length=6)),
            ],
        ),
    ]
