# Generated by Django 4.1 on 2023-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_customuser_credict_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
