# Generated by Django 4.1 on 2023-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_customuser_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
    ]
