# Generated by Django 4.1 on 2023-02-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_customuser_is_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_author',
            new_name='author',
        ),
    ]
