# Generated by Django 4.1 on 2023-02-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_is_author_customuser_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='author',
            new_name='Book_Author',
        ),
    ]
