# Generated by Django 4.1 on 2023-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_customuser_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Book_Author',
            field=models.BooleanField(default=True),
        ),
    ]
